### PR TITLE
Adding a docker container for this application

### PR DESCRIPTION
**Pull request by Ricardicus**
One can now generate these plots with a user interface :)

### CODE REVIEW

**Comment by karvla** [comment]
Cool! I'm trying to test the docker container but `docker build -t covid19-confirmed-cases:1.0 -f docker/Dockerfile` gives me this: 
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by Ricardicus** [comment]
try:
`
docker build -t covid19-confirmed-cases:1.0 -f docker/Dockerfile .`

notice the dot at the end :)

**Comment by Ricardicus** [comment]
Also, make sure you stand in the root folder of the project (I copy files from there, and when building images it is important to have the right context)

**Comment by karvla** [comment]
Oh shoot I missed the dot. It's working now

**Comment by Ricardicus** [comment]
nice :D I have built a way to launch terminal commands from the javascript, and it is safe because it runs in a container. I hope it is easy to it modify at will. 
It would be nice to have it list the number also, then it could also 
make a list of "new cases" so that a trend can be seen.

**Comment by Ricardicus** [comment]
It is a start, it takes some time to generate plots and I just wait 4 seconds and then I output the file "output.png" regardless if it worked or not ... Could be improved!

**Comment by karvla** [comment]
I fixed some minor stuff! Well done!:)

**Comment by Ricardicus** [comment]
Thank you! It is fun to contribute.

**Pull request merged**
