### PR TITLE
Major improvements

### PR DESCRIPTION
**Pull request by ErikBjare**
Had a bunch of changes I never pushed or made a PR for.

Invite me to the repo to prevent this in the future ;)

### CODE REVIEW

**Comment by ErikBjare** [comment]
@Ricardicus This changes the CLI interface for `covid19count.py` slightly so it might mess with your web app. You might also want to add support for the new options :)

**Comment by Ricardicus** [comment]
Cool will check it out.

**Comment by Ricardicus** [comment]
> @Ricardicus This changes the CLI interface for `covid19count.py` slightly so it might mess with your web app. You might also want to add support for the new options :)

Please update the README so I see what these new options do! In the meantime I will dig into the code. :)

**Comment by ErikBjare** [comment]
Will do at some point, but for now the script should be somewhat self
documenting. Just run it with --help to see the subcommands and options :)

**Comment by Ricardicus** [comment]
I figured out most of it I think! Updating the GUI thing.

**Comment by Ricardicus** [comment]
... and very neat work!

**Pull request merged**
